services:
  - type: web
    name: firstscanit-qr-frontend
    env: static
    buildCommand: echo "No build needed"
    staticPublishPath: ./frontend

  - type: web
    name: firstscanit-qr-api
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn --bind 0.0.0.0:$PORT api.app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: FLASK_ENV
        value: production
